name: encontraste
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0

  provider: ^4.0.3
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.2+1
  get_it: ^3.1.0
  datetime_picker_formfield:
  


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
  