name: encontraste
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.0
  provider: ^4.0.3
  firebase_core: ^0.4.4
  
  firebase_auth: ^0.14.0+5
  
  google_sign_in: ^4.2.0

  cloud_firestore: ^0.13.2+1
  get_it: ^3.1.0
  datetime_picker_formfield:
  
  simple_animations: ^1.3.11
  
  flutter_masked_text: ^0.8.0
  
  camera: ^0.5.7+4
  path_provider: ^1.6.5
  flutter_native_image: ^0.0.5+2
  flutter_image_compress: ^0.6.5+1
  image_picker: ^0.6.4  
  exif: ^1.0.2

  
  firebase_storage: ^3.0.8 
  firebase_analytics: ^5.0.6

  agora_rtm: ^0.9.10
  agoravoice: ^0.0.3  
  agora_rtc_engine: 1.0.5
  permission_handler: ^3.0.0
  flutter_colorpicker: ^0.3.2
  painter: ^0.3.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
  